blank_issues_enabled: true
contact_links:
  - name: Preview application online 🔥
    url: https://zoo-js.github.io/zoo-issue-helper/
    about: You can apply for online preview by clicking the link on the right. 你可以通过点击右侧链接在线预览进行申请。
