name: Check need info

on:
  schedule:
    - cron: "0 12 */7 * *"

jobs:
  check-need-info:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install
        run: yarn

      - name: node js
        run: node ./script/check-need-info.js
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
